##define file
Reads:
 - class: File
   location: "/mnt/d/bcr_test/t1.r1.fq.gz"

 - class: File
   location: "/mnt/d/bcr_test/t1.r2.fq.gz"
##define tools path
mixcr_path:
  class: File
  location: "/home/idsz/miniconda3/envs/py3/bin/mixcr"
##define  imgt_json path:
mixcr_json:
  class: File
  location: "/mnt/d/bcr_test/imgt.202312-3.sv8_rabbit.json"
version: 1
threads: 16